theme: jekyll-theme-midnight

baseurl: /swagger-deepdive
title: Menagerie
description: Explores different features of Swagger and Springfox in-depth.

author: Indra Basak

logo: ./img/logo_80px.png
docs: https://github.com/indrabasak/swagger-deepdive/wiki
#demo: